### ISSUE TITLE
ImportError: cannot import name 'Annotated' from 'typing'

### ISSUE THREAD

**Issue by lmar76** [avalentino/bpack#1]
I have installed `bpack` 0.8 library on python3.9, python3.8 and python3.7. On python 3.9 I have not detected any error but in python3.8 and python3.7, trying to import `bpack`, I got the following errors:

```
% python
Python 3.8.12 (default, Oct 12 2021, 06:23:56) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import bpack
Traceback (most recent call last):
  File "/usr/local/opt/anaconda3/envs/py38/lib/python3.8/site-packages/bpack/typing.py", line 7, in <module>
    from typing_extensions import _tp_cache                 # noqa
ImportError: cannot import name '_tp_cache' from 'typing_extensions' (/usr/local/opt/anaconda3/envs/py38/lib/python3.8/site-packages/typing_extensions.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/opt/anaconda3/envs/py38/lib/python3.8/site-packages/bpack/__init__.py", line 7, in <module>
    from .descriptors import (                                      # noqa: F401
  File "/usr/local/opt/anaconda3/envs/py38/lib/python3.8/site-packages/bpack/descriptors.py", line 11, in <module>
    import bpack.typing
  File "/usr/local/opt/anaconda3/envs/py38/lib/python3.8/site-packages/bpack/typing.py", line 13, in <module>
    from typing import Annotated, get_origin, get_args
ImportError: cannot import name 'Annotated' from 'typing' (/usr/local/opt/anaconda3/envs/py38/lib/python3.8/typing.py)
```

and

```
% python
Python 3.7.11 (default, Jul 27 2021, 07:03:16) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import bpack
Traceback (most recent call last):
  File "/usr/local/opt/anaconda3/envs/py37/lib/python3.7/site-packages/bpack/typing.py", line 7, in <module>
    from typing_extensions import _tp_cache                 # noqa
ImportError: cannot import name '_tp_cache' from 'typing_extensions' (/usr/local/opt/anaconda3/envs/py37/lib/python3.7/site-packages/typing_extensions.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/opt/anaconda3/envs/py37/lib/python3.7/site-packages/bpack/__init__.py", line 7, in <module>
    from .descriptors import (                                      # noqa: F401
  File "/usr/local/opt/anaconda3/envs/py37/lib/python3.7/site-packages/bpack/descriptors.py", line 11, in <module>
    import bpack.typing
  File "/usr/local/opt/anaconda3/envs/py37/lib/python3.7/site-packages/bpack/typing.py", line 13, in <module>
    from typing import Annotated, get_origin, get_args
ImportError: cannot import name 'Annotated' from 'typing' (/usr/local/opt/anaconda3/envs/py37/lib/python3.7/typing.py)
```

The packages installed in my python3.8 and python3.7 environments are:

```
# packages in environment at /usr/local/opt/anaconda3/envs/py38:
#
# Name                    Version                   Build  Channel
bitstruct                 8.11.1           py38h96a0964_1    conda-forge
bpack                     0.8.0                    pypi_0    pypi
ca-certificates           2021.10.8            h033912b_0    conda-forge
certifi                   2021.10.8        py38h50d1736_1    conda-forge
libcxx                    12.0.0               h2f01273_0  
libffi                    3.3                  hb1e8313_2  
ncurses                   6.3                  hca72f7f_2  
openssl                   1.1.1l               h0d85af4_0    conda-forge
pip                       21.2.4           py38hecd8cb5_0  
python                    3.8.12               h88f2d9e_0  
python_abi                3.8                      2_cp38    conda-forge
readline                  8.1                  h9ed2024_0  
setuptools                58.0.4           py38hecd8cb5_0  
sqlite                    3.36.0               hce871da_0  
tk                        8.6.11               h7bc2e8c_0  
typing-extensions         4.0.0                    pypi_0    pypi
wheel                     0.37.0             pyhd3eb1b0_1  
xz                        5.2.5                h1de35cc_0  
zlib                      1.2.11               h1de35cc_3  
```

```
# packages in environment at /usr/local/opt/anaconda3/envs/py37:
#
# Name                    Version                   Build  Channel
bitstruct                 8.11.1           py37h271585c_1    conda-forge
bpack                     0.8.0                    pypi_0    pypi
ca-certificates           2021.10.8            h033912b_0    conda-forge
certifi                   2021.10.8        py37hf985489_1    conda-forge
libcxx                    12.0.0               h2f01273_0  
libffi                    3.3                  hb1e8313_2  
ncurses                   6.3                  hca72f7f_2  
openssl                   1.1.1l               h0d85af4_0    conda-forge
pip                       21.2.2           py37hecd8cb5_0  
python                    3.7.11               h88f2d9e_0  
python_abi                3.7                     2_cp37m    conda-forge
readline                  8.1                  h9ed2024_0  
setuptools                58.0.4           py37hecd8cb5_0  
sqlite                    3.36.0               hce871da_0  
tk                        8.6.11               h7bc2e8c_0  
typing-extensions         4.0.0                    pypi_0    pypi
wheel                     0.37.0             pyhd3eb1b0_1  
xz                        5.2.5                h1de35cc_0  
zlib                      1.2.11               h1de35cc_3  
```

**Comment by avalentino** [comment]
Hi @lmar76, thanks for reporting.
The issue should be fixed now in the main branch.
Please give it a try and let me know if it works for you.
I will make a new release and conda packages ASAP.

**Comment by lmar76** [comment]
Ciao Antonio,

Grazie! ora funziona!

Ciao,

Luca



From:   "Antonio Valentino" ***@***.***>
To:     "avalentino/bpack" ***@***.***>
Cc:     "Luca Mariani" ***@***.***>, "Mention" 
***@***.***>
Date:   30/11/2021 17:42
Subject:        Re: [avalentino/bpack] ImportError: cannot import name 
'Annotated' from 'typing' (Issue #1)



Hi @lmar76, thanks for reporting.
The issue should be fixed now in the main branch.
Please give it a try and let me know if it works for you.
I will make a new release and conda packages ASAP.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 



This message is intended only for the recipient(s) named above. It may contain proprietary information and/or
protected content. Any unauthorised disclosure, use, retention or dissemination is prohibited. If you have received
this e-mail in error, please notify the sender immediately. ESA applies appropriate organisational measures to protect
personal data, in case of data privacy queries, please contact the ESA Data Protection Officer ***@***.***).
